version: '3'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/application
    restart: always
    networks:
      - myapp

networks:
  myapp: